  MODULE('INFOPER025.CLW')
FormCertificado        PROCEDURE                      !Form CERTIFICADOS
AusenciaPorEmpleado    PROCEDURE                      !Window
ProcesarEstadosAusencias PROCEDURE                    !Browse the DETALLE_LICENCIA file
AusenciaPorSector      PROCEDURE                      !Window
AusenciaPorMotivo      PROCEDURE                      !Window
Motivos                PROCEDURE                      !Browse the MOTIVO_AUSENCIA file
ReporteMedico          PROCEDURE(long,short)          !Report MÉDICOS File
FechasCumpleaños       PROCEDURE                      !Window
  END
