  MODULE('INFOPER034.CLW')
ProcesarAdelantoSueldo PROCEDURE                      !Browse the DETALLE_LICENCIA file
ProcesarAdelantoRetribucionLicencia PROCEDURE         !Browse the DETALLE_LICENCIA file
ProcesarASueldoRetribucionLicencia_DiasdeViaje PROCEDURE !Browse the DETALLE_LICENCIA file
_ProcesarASueldoRetribucionLicencia_DiasdeViaje PROCEDURE !Browse the DETALLE_LICENCIA file
Procesar_RetribucionesASueldo PROCEDURE               !Browse the LICENCIA file
Provision              PROCEDURE                      !Browse the PROVISION file
UpdatePROVISION        PROCEDURE                      !Form PROVISION
ProcesarAsientoProvision PROCEDURE                    !Browse the DETALLE_PROVISION file
LicenciaCtaContable    PROCEDURE                      !Browse the CTA_CONTABLE file
  END
