  MODULE('INFOPER022.CLW')
LicenciaPorSector      PROCEDURE                      !Window
Sectores               PROCEDURE                      !Browse the SECTOR file
ReportLicenciasPorSector PROCEDURE(long)              !Report the LICENCIA File
EmpleadosEdit          PROCEDURE                      !Browse the EMPLEADOS file
EditarEmpleados        PROCEDURE                      !Form EMPLEADOS
LicenciaPorEmpleado    PROCEDURE                      !Window
Feriados               PROCEDURE                      !Browse the FERIADOS file
administradoHorasExtras PROCEDURE                     !Process the HORASEXTRASCVS File
UpdateFERIADOS         PROCEDURE                      !Form FERIADOS
CuentasContables       PROCEDURE                      !Browse the CTA_CONTABLE file
  END
