  MODULE('USEREDIT002.CLW')
SSEC::UpdateUser       PROCEDURE                      !Update the SSEC::User File
SSEC::SelectGroup      PROCEDURE                      !Browse the SSEC::User File
SSEC::UpdateUIG:User   PROCEDURE
SSEC::GroupAccessState FUNCTION(),BYTE
SSEC::BrowseUser       PROCEDURE                      !Browse the SSEC::User File
SSEC::PrintGroupByAccess PROCEDURE                    !Report the SSEC::User File
SSEC::PrintGroupByName PROCEDURE                      !Report the SSEC::User File
SSEC::PrintUserByAccess PROCEDURE                     !Report the SSEC::User File
SSEC::PrintUserByGroup PROCEDURE                      !Report the SSEC::User File
SSEC::PrintUserByName  PROCEDURE                      !Report the SSEC::User File
SSEC::UserEdit         PROCEDURE
  END
